apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproj-user-api
  # namespace: my-namespace
  labels:
    app: finalproj-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalproj-user-api
  template:
    metadata:
      labels:
        app: finalproj-user-api
    spec:
      containers:
        - name: finalproj-user-api
          image: jooankrah/finalproj-user-api-image:latest
          ports:
            - containerPort: 3000
