apiVersion: v1
kind: Service
metadata:
  name: finalproj-user-api
  # namespace: my-namespace
  labels:
    app: finalproj-user-api
spec:
  selector:
    app: finalproj-user-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
